config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  namespace :admin do
	  resources :products do
	    # resources :product_comments, shallow: true
	  end
	  # resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_product.rb
# == Schema Information
#
# Table name: categories_products
#
#  category_id :integer          not null
#  product_id  :integer          not null
#
# Indexes
#
#  index_categories_products_on_category_id_and_product_id  (category_id,product_id)
#  index_categories_products_on_product_id_and_category_id  (product_id,category_id)
#

class CategoriesProduct < ApplicationRecord
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id            :integer          not null, primary key
#  title         :string(255)      not null
#  serial_number :integer          default(0), not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Category < ApplicationRecord
	has_and_belongs_to_many :products
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  mobile     :string(255)
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ApplicationRecord
	
	has_many :shopping_carts
	has_many :products, through: :shopping_carts
	has_many :product_comments
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id           :integer          not null, primary key
#  picture      :string(255)
#  price        :float(24)        not null
#  status       :integer          default("waiting"), not null
#  stock_number :integer          default(0), not null
#  title        :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
require 'carrierwave/orm/activerecord'

class Product < ApplicationRecord

	enum status: { waiting: 0, actived: 1, deleted: 2 }, _suffix: true
	mount_uploader :picture, ProductPictureUploader

	has_many :shopping_carts # 购物车
	has_many :product_comments, dependent: :destroy # 商品评价
	has_many :customer, through: :shopping_carts # 购物车
	
	has_and_belongs_to_many :categories # 商品种类
end

app/models/product_comment.rb
# == Schema Information
#
# Table name: product_comments
#
#  id          :integer          not null, primary key
#  content     :string(255)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  customer_id :integer
#  product_id  :integer
#
# Indexes
#
#  index_product_comments_on_customer_id  (customer_id)
#  index_product_comments_on_product_id   (product_id)
#

class ProductComment < ApplicationRecord
	belongs_to :product,counter_cache: true # 商品
	belongs_to :customer # 用户
end

app/models/shopping_cart.rb
# == Schema Information
#
# Table name: shopping_carts
#
#  id             :integer          not null, primary key
#  product_number :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  customer_id    :integer
#  product_id     :integer
#
# Indexes
#
#  index_shopping_carts_on_customer_id  (customer_id)
#  index_shopping_carts_on_product_id   (product_id)
#

class ShoppingCart < ApplicationRecord
	belongs_to :customer
	belongs_to :product
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout "admin_application"
end

app/controllers/admin/category_controller.rb
class Admin::CategoryController < ApplicationController
	before_filter :find_category


	def index

	end

	

	private
	def find_category
		@category = Category.find(params[:id]) if params[:id]
	end

	def category_params
		params.permit(:category, :title, :serial_number)
	end

end

app/controllers/admin/product_comments_controller.rb
class Admin::ProductCommentsController < Admin::ApplicationController
  before_action :set_product_comment, only: [:show, :edit, :update, :destroy]

  # GET /product_comments
  # GET /product_comments.json
  def index
    @product_comments = ProductComment.all
  end

  # GET /product_comments/1
  # GET /product_comments/1.json
  def show
  end

  # GET /product_comments/new
  def new
    @product_comment = ProductComment.new
  end

  # GET /product_comments/1/edit
  def edit
  end

  # POST /product_comments
  # POST /product_comments.json
  def create
    @product_comment = ProductComment.new(product_comment_params)

    respond_to do |format|
      if @product_comment.save
        format.html { redirect_to @product_comment, notice: 'Product comment was successfully created.' }
        format.json { render :show, status: :created, location: @product_comment }
      else
        format.html { render :new }
        format.json { render json: @product_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_comments/1
  # PATCH/PUT /product_comments/1.json
  def update
    respond_to do |format|
      if @product_comment.update(product_comment_params)
        format.html { redirect_to @product_comment, notice: 'Product comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_comment }
      else
        format.html { render :edit }
        format.json { render json: @product_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_comments/1
  # DELETE /product_comments/1.json
  def destroy
    @product_comment.destroy
    respond_to do |format|
      format.html { redirect_to product_comments_url, notice: 'Product comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_comment
      @product_comment = ProductComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_comment_params
      params.require(:product_comment).permit(:content)
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController


	before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit
	end


	def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to product, notice: 'Product comment was successfully destroyed.' }
      format.json { head :no_content }
    end
	end


	private

	  def set_product
			@product = Product.find(params[:id]) if params[:id]
		end

		def product_params
			params.require(:product).permit(:title,:price,:stock_number,:status,:picture)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_comments_helper.rb
module ProductCommentsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/admin/product_comments/_form.html.erb
<%= form_for(product_comment) do |f| %>
  <% if product_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_comment.errors.count, "error") %> prohibited this product_comment from being saved:</h2>

      <ul>
      <% product_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/product_comments/edit.html.erb
<h1>Editing Product Comment</h1>

<%= render 'form', product_comment: @product_comment %>

<%= link_to 'Show', @product_comment %> |
<%= link_to 'Back', product_comments_path %>

app/views/admin/product_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_comments.each do |product_comment| %>
      <tr>
        <td><%= product_comment.content %></td>
        <td><%= link_to 'Show', product_comment %></td>
        <td><%= link_to 'Edit', edit_product_comment_path(product_comment) %></td>
        <td><%= link_to 'Destroy', product_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Comment', new_product_comment_path %>

app/views/admin/product_comments/new.html.erb
<h1>New Product Comment</h1>

<%= render 'form', product_comment: @product_comment %>

<%= link_to 'Back', product_comments_path %>

app/views/admin/product_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @product_comment.content %>
</p>

<%= link_to 'Edit', edit_product_comment_path(@product_comment) %> |
<%= link_to 'Back', product_comments_path %>

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :stock_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :stock_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:stock_number) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :picture, :class => 'form-control' %>
    </div>
    <%=f.error_span(:picture) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:stock_number) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, admin_product_path(product) %></td>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.stock_number %></td>
        <td><%= product.status %></td>
        <td><%= product.picture %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      admin_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_product_path,
            :class => 'btn btn-primary' %>

app/views/admin/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @product.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stock_number) %>:</strong></dt>
  <dd><%= @product.stock_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @product.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd>
    <%= image_tag @product.picture, size: "400x300" %>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<h2>hello, X</h2>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Strawberry" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Strawberry</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strawberry</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>